version: "3.9"
services:
  app:
    build: https://github.com/matthewsaunders/link-shortener-app.git#main
    ports:
      - 3000:3000
    restart: always
    networks:
      - shrtnr-backend-network

  api:
    build: https://github.com/matthewsaunders/link-shortener-api.git#main
    ports:
      - 4000:4000
    restart: always
    networks:
      - shrtnr-backend-network
    stdin_open: true
    tty: true
    depends_on:
      - db

  db:
    image: library/postgres:13-alpine
    ports:
      - 5432:5432
    restart: always
    networks:
      - shrtnr-backend-network
    volumes:
      - shrtnr-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=shrtnr
      - POSTGRES_PASSWORD=password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
    - shrtnr-backend-network

volumes:
  shrtnr-db:
    driver: local

networks:
  shrtnr-backend-network:
    driver: bridge
